### ISSUE TITLE
getAttributes, getPermissions forces 1 db call per role

### ISSUE THREAD

**Issue by azhang** [yanickrochon/rbac-a#4]
I've made some changes in my fork of this project in an attempt to optimize my particular use case with mongodb. However, I've realized that the changes may be beneficial universally - I'd love to hear what you think. 

https://github.com/azhang/rbac-a/tree/refactor
specific commit: https://github.com/azhang/rbac-a/commit/5263cbff60ab78dcdb9320bbc13bdfb2b92e4326

Currently, the `getAttributes` and `getPermissions` functions inside providers are called once per role:

```
// (inside filterRolesByAttributes)
return Promise.all(Object.keys(roles).map(function (role) {
  return _attr(role)... // which calls provider.getAttributes n times, once for each role.
}));
```

However, this iteration can be moved to individual provider implementations - call `provider.getAttributes(roles)`, and get back an object keyed by role ({role1: ['attribute1']}). Simple change, but best case improves `n` db calls to 1 db call per `check`.

Similarly, with `getPermissions`

```
  return Promise.all(Object.keys(userRoles).map(function (role) {
    return getRolePermissions(emitter, user, role, userRoles[role], provider);
    // which calls provider.getPermissions(role) n times, once for each role.
  }))
```

can be replaced with `provider.getPermissions(userRoles)` which returns an object {role1: ['permission1']}.

**Comment by yanickrochon** [comment]
I'll gladly take a look at it! For my use case, users had only a few roles, and they were cached once fetched, so it didn't bother to make n calls once in a while. The only important thing is that, in a RBAC system, roles may be hierarchical. Once the role orders have been determine, indeed, permissions and attributes may be fetched in batch.

**Comment by yanickrochon** [comment]
This will be part of the v2.0.0 release. I'm am closing this because of how it uses `Bluebird` and would create a conflict from the last commits.

The refactor *will* have `getRolePermissions(roles)` instead of the current singular implementation.
