### ISSUE TITLE
If attribute defined in role's list but not implemented there has to be Exception

### ISSUE THREAD

**Issue by valVk** [yanickrochon/rbac-a#6]
```
{
  "roles": {
    "guest": {
    },
    "reader": {
      "permissions": ["read"],
      "inherited": ["guest"]
    },
    "writer": {
      "permissions": ["create"],
      "inherited": ["reader"]
    },
    "editor": {
      "permissions": ["update"],
      "inherited": ["reader"],
      "attributes": ["dailySchedule"]
    },
}
```
Expected message eg. `Attribute dailySchedule has to be implemented in AttributesManager()`
Recieved: NaN,

```javascript
  validate(attribute, user, role, params) {
    if (typeof attribute !== 'string') {
      throw new TypeError('Attribute should be a string');
    } else if (!attribute) {
      throw new TypeError('Attribute name cannot be empty');
    } else if (!this._attributes[attribute]) {
      //throw new TypeError('Unknown attribute : ' + attribute);
      return false;
    }

    return this._attributes[attribute](user, role, params);
  }

}
```

**Comment by yanickrochon** [comment]
Good catch! I'll add that ASAP!

**Comment by valVk** [comment]
Probably there has to be some kind of pre validation of JSON object to get whether this object correct or not. Because this exception will be thrown only if this rule will be matched and not when application starts

**Comment by yanickrochon** [comment]
Well, no, there cannot be pre-validation because `attribute` is a parameter and `_attributes` is the class' field; one is given at run-time, the other can be manipulated externally. Thus, both make it impossible to validate first hand. The API would need to be changed in order to do so and, for the current design, I had fine grain testing in mind. Because an `AttributeManager` is independent from the `Provider`.

**Comment by valVk** [comment]
This was just as proposal. For me I'm going to create a wrapper around RBAC's JSON object and just iterates through attributes, call them if they are exist and catch exceptions in case they will be thrown. Simple, easy and stupid approach )

**Comment by yanickrochon** [comment]
This has been addressed in the most recent commits. By default, the `AttributesManager` will be silent, but providing the option `ignoreMissingAttributes: false` will throw when validating against undefined attributes.

And I just realized that I forgot to mention that in the README :smile:
